export const Film =[
    {
      id:Math.floor(Math.random() * 100000),
      title:"True Spirit ", 
      description:"This inspirational film tells the true story of a teenager's incredible sea voyage.", 
      posterURL:"https://m.media-amazon.com/images/M/MV5BZDliNjMwYjktMGI5Zi00OWVkLWJmOWYtNjAxNGI1YzA3MTYxXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg",
      videoURL:"https://www.youtube.com/watch?v=UPYD9dw6jmA",
      Origine: "Australian ",
      Datesortie: "2023",
      Genre: "Biography",
      duree: "  1h 49min",
      Qualite: "HDLight",
      rating:"3",
    },
      {
        id:Math.floor(Math.random() * 100000),
        title:"Re/Member", 
        description:"Six high schoolers stuck in a murderous time loop must find the scattered remains of an unknown victim to break the curse and finally see another day.", 
        posterURL:"https://i.mydramalist.com/R6NOg_4f.jpg",
        videoURL:"https://www.youtube.com/watch?v=Y8yvXoyLPvM",
        Origine: "Japanese ",
        Datesortie: "2022",
        Genre: "Horror",
        duree: "2h 15min",
        Qualite: "HDLight",
        rating:"2",
  
  
      },
      {
        id:Math.floor(Math.random() * 100000),
        title:"JOKER", 
        description:"Set in 1981, it follows Arthur Fleck, a failed clown and aspiring stand-up comic whose descent into mental illness and nihilism inspires a violent countercultural revolution against the prosperous in a decaying Gotham City.", 
        posterURL:"https://mir-s3-cdn-cf.behance.net/project_modules/fs/cbd1d778763331.5cae347d06d38.jpg",
        videoURL:"https://www.youtube.com/watch?v=zAGVQLHvwOY",
        Origine: "U.S.A.",
        Datesortie: "2019",
        Genre: "Thriller",
        duree: "2h 2min",
        Qualite: "HDLight",
        rating:"5",
      },
      {
        id:Math.floor(Math.random() * 100000),
        title:"Avatar", 
        description:"It follows a blue-skinned humanoid Na'vi named Jake Sully (Worthington) as he and his family, under renewed human threat, seek refuge with the aquatic Metkayina clan of Pandora, a habitable exomoon on which they live.", 
        posterURL:"https://cdnb.artstation.com/p/assets/images/images/029/128/171/large/giulia-talocco-avatar.jpg",
        videoURL:"https://www.youtube.com/watch?v=d9MyW72ELq0",
        Origine: "New Zealand",
        Datesortie: "2022",
        Genre: "Aventure",
        duree: " 3h 12min",
        Qualite: "HDLight",
        rating:"4",
      },
      {
        id:Math.floor(Math.random() * 100000),
        title:"The Private Life ", 
        description:"Depuis l’aube de l’humanité, les Éternels, un groupe de héros venus des confins de l’univers, protègent la Terre. Lorsque les Déviants, des créatures monstrueuses que l’on croyait disparues depuis longtemps, réapparaissent mystérieusement, les Éternels sont à nouveau obligés de se réunir pour défendre l’humanité…", 
        posterURL:"https://www.cpasfini.me/uploads/posts/2022-02/1645125416_19eec0c6521a602e6af1c0b81b64ae9d.jpg",
        videoURL:"https://www.youtube.com/embed/S06abmL_lS0",
        Origine: "U.S.A.",
        Datesortie: "2021",
        Genre: " Drame",
        duree: " 1h 11min",
        Qualite: "HDLight",
        rating:"2",
      },
      
      {
        id:Math.floor(Math.random() * 100000),
        title:"The In Between", 
        description:"Après avoir perdu son grand amour dans un tragique accident, une adolescente au cœur brisé se met à croire qu'il lui envoie des signes d'outre-tombe.", 
        posterURL:"https://www.cpasfini.me/uploads/posts/covers/29880d654d2591e9f1ac091466e600ab.jpg",
        videoURL:"https://www.youtube.com/embed/l5i6U22MaBo",
        Origine: "U.S.A.",
        Datesortie: "2021",
        Genre: " ramance",
        duree: "  1h 55min",
        Qualite: "HDLight",
        rating:"5",
      },
      {
        id:Math.floor(Math.random() * 100000),
        title:"Inception", 
        description:" A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.", 
        posterURL:"https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_FMjpg_UX1000_.jpg",
        videoURL:"https://www.youtube.com/watch?v=YoHD9XEInc0",
        Origine: "U.S.A.",
        Datesortie: "2010",
        Genre: " Action",
        duree: " 2h 28min",
        Qualite: "HDLight",
        rating:"5",
      },
      
      {
        id:Math.floor(Math.random() * 100000),
        title:"The Door Into Summer", 
        description:"An inventor of robotics technology is robbed by his girlfriend and business partner and sent to the future via cryogenic sleep. But when he awakes 30 years later, he is assisted by a humanoid robot originally his own creation.", 
        posterURL:"https://media.senscritique.com/media/000019761279/300/une_porte_sur_l_ete.jpg",
        videoURL:"https://www.youtube.com/watch?v=M39FNAlhPnU",
        Origine: "Japanese",
        Datesortie: "2021",
        Genre: "  Romance",
        duree: "  1h 58min",
        Qualite: "HDLight",
        rating:"4",
      },
      ]; 